# Game settings
RES = WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 720
SCROLL_SPEED = 200 # miliseconds

# Bird settings
BIRD_POS = WINDOW_WIDTH //4, WINDOW_HEIGHT//4
BIRD_SCALE = 0.8
BIRD_ANIMATION_TIME = 150 # miliseconds

# Ground
GROUND_HEIGHT = WINDOW_HEIGHT // 12
GROUND_Y = WINDOW_HEIGHT - GROUND_HEIGHT

# Gravity
GRAVITY = 0.7
BIRD_JUMP = -10
# angle
BIRD_JUMP_ANGLE = 25 # degrees

# pipes settings
PIPE_WIDTH = 120
PIPE_HEIGHT = WINDOW_HEIGHT
# pipes gap
PIPES_GAP_X = 450
PIPES_GAP_Y = 220
HALF_GAP_Y = PIPES_GAP_Y // 2

